version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
      - TZ=Asia/Tokyo
    ports:
      - "5433:5433"
    command: ["postgres", "-p", "5433"]

  test-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_database
      - TZ=Asia/Tokyo
    ports:
      - "5434:5433"
    command: ["postgres", "-p", "5433"]
