#name: api lint
#
#on:
#  pull_request:
#    paths:
#      - 'api/**'
#      - '.github/workflows/api.lint.yml'
#    branches-ignore:
#      - 'renovate/*'
#
#jobs:
#  check:
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        shell: bash
#        working-directory: 'api'
#    permissions:
#      # Give the default GITHUB_TOKEN write permission to commit and push the
#      # added or changed files to the repository.
#      contents: write
#
#    steps:
#      - uses: actions/checkout@v4 # checks-out the repository under $GITHUB_WORKSPACE
#      - uses: actions/setup-node@v4
#        with:
#          node-version: '20'
#      - run: yarn
#
#      - name: format
#        run: yarn format
#
#      - name: auto commit
#        uses: stefanzweifel/git-auto-commit-action@v5
#        with:
#          commit_message: Auto commit with fmt
#          branch: ${{ github.head_ref }}
#
#      - name: lint
#        uses: reviewdog/action-eslint@v1
#        with:
#          workdir: 'api'
#          eslint_flags: '"{src,apps,libs,test}/**/*.ts" --fix'
#          level: warning
