name: Playwright Tests

on: pull_request

jobs:
  check:
    runs-on: buildjet-8vcpu-ubuntu-2204
    defaults:
      run:
        shell: bash
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run Docker
        run: docker compose up -d
        working-directory: 'api'
      - name: Api Install Dependencies
        run: yarn
        working-directory: 'api'
      - name: Copy Api .env
        run: cp .env.sample .env
        working-directory: 'api'
      - name: Api Build
        run: yarn build
        working-directory: 'api'
      - name: Migration
        run: |
          yarn typeorm migration:run -d ./db/data-source.ts
          yarn seed --name GenesisSeeder
        working-directory: 'api'
      - name: Start Backend (with logging)
        working-directory: 'api'
        run: |
          nohup yarn start:dev > backend.log 2>&1 &
          echo "Waiting for NestJS to start..."
          for i in {1..15}; do
            if grep -q "Nest application successfully started" backend.log; then
              echo "NestJS is up."
              break
            fi
            sleep 1
          done
      - name: Install Frontend Dependencies
        run: yarn
        working-directory: 'frontend-react'
      - name: Copy Frontend .env
        run: cp .env.sample .env
        working-directory: 'frontend-react'
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
        working-directory: 'frontend-react'
      - name: Run Playwright tests
        run: yarn playwright test
        working-directory: 'frontend-react'
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend-react/playwright-report/
          retention-days: 30
      - name: Upload Backend Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-log
          path: api/backend.log
          retention-days: 30