name: Playwright Tests

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run Docker
        run: docker compose up -d
        working-directory: 'api'
      - name: Api Install Dependencies
        run: yarn
        working-directory: 'api'
      - name: Copy Api .env
        run: cp .env.sample .env
        working-directory: 'api'
      - name: Api Build
        run: yarn build
        working-directory: 'api'
      - name: Migration
        run: |
          yarn typeorm migration:run -d ./db/data-source.ts
          yarn seed --name GenesisSeeder
        working-directory: 'api'
      - name: Run Server
        run: screen -dmS nestjs yarn start:dev
        working-directory: 'api'
      - name: Install Frontend Dependencies
        run: yarn
        working-directory: 'frontend-react'
      - name: Copy Frontend .env
        run: cp .env.sample .env
        working-directory: 'frontend-react'
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
        working-directory: 'frontend-react'
      - name: Run Playwright tests
        run: yarn playwright install --with-deps
        working-directory: 'frontend-react'
      - uses: actions/upload-artifact@v4
        if: ${{ failure() && steps.e2e.conclusion == 'failure' }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30